name: dart_movie_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0
  envied: ^0.5.4+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  uuid: ^4.4.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
